import { cp, mkdir, mkdtemp, readdir, rename } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { generateIcons } from './icons.js';
const root = fileURLToPath(new URL('../', import.meta.url));
await generateIcons(new URL('../assets/', import.meta.url));
execFileSync(process.execPath, ['scripts/check.js'], { cwd: root, stdio: 'inherit' });
const staging = await mkdtemp(join(tmpdir(), 'mailbox-mint-package-'));
const items = ['manifest.json', 'background', 'popup', 'options', 'lib', 'assets', 'migrations', 'README.md', 'PRIVACY.md'];
for (const item of items) await cp(join(root, item), join(staging, item), { recursive: true });
const archive = join(staging, 'cloud-mail-mailbox-mint.zip');
execFileSync('/usr/bin/zip', ['-X', '-qr', archive, ...items], { cwd: staging });
await mkdir(join(root, 'dist'), { recursive: true });
await rename(archive, join(root, 'dist/cloud-mail-mailbox-mint.zip'));
const unpacked = join(root, 'dist/cloud-mail-mailbox-mint');
await mkdir(unpacked, { recursive: true });
for (const item of items) await cp(join(staging, item), join(unpacked, item), { recursive: true });
const existing = await readdir(unpacked);
if (existing.some(item => !items.includes(item))) throw new Error('Unexpected file in unpacked artifact; inspect before shipping.');
console.log(`Ready: ${unpacked}\nZIP: ${join(root, 'dist/cloud-mail-mailbox-mint.zip')}`);
